#!/usr/bin/env bash
#
# Run pre test checks
#
set -e

echo '[script/pre_test] Running go vet'
go vet ./...

echo '[script/pre_test] Running golint'
go list ./... | grep -v /vendor/ | xargs -L1 golint

# vim: ft=sh:
